collection = set()
collection.add(1)
collection.add(2)
collection.add(2)
collection.add(3)
print(collection)
collection.remove(2)
print(collection)
collection.remove(4)
print(collection)
collection.pop()
print(collection)
collection.clear()
print(collection)