list  = [2,1,3]
print(list.append(4))
print(list)
print(list.sort())
print(list)
print(list.sort(reverse = True))
print(list)
print(list.reverse())
print(list)
print(list.insert(1,8))
print(list)
print(list.remove(1))
print(list)
print(list.pop(0))
print(list)